**Section A : Data Structures & Control Structures**

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [93]:
list1=[10,3,4,5,8]

In [94]:
# append
list1.append(6)
list1

[10, 3, 4, 5, 8, 6]

In [95]:
# entend
list1.extend([7,9])
list1

[10, 3, 4, 5, 8, 6, 7, 9]

In [96]:
# insert
list1.insert(11,2)
list1

[10, 3, 4, 5, 8, 6, 7, 9, 2]

In [97]:
# remove
list1.remove(2)
list1

[10, 3, 4, 5, 8, 6, 7, 9]

In [98]:
# pop
list1.pop(5)
list1

[10, 3, 4, 5, 8, 7, 9]

In [99]:
# clear
list1.clear()
list1

[]

In [100]:
# index
list1=[10,3,4,5,8]
list1.index(5)

3

In [101]:
# count
list1.count(3)

1

In [102]:
# sort
list1.sort()
list1

[3, 4, 5, 8, 10]

In [103]:
# reverse
list1.reverse()
list1

[10, 8, 5, 4, 3]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [104]:
# Create a tuple
tuple1=('Harsha','Vishnu','teju')

In [105]:
# trying to change second name in tuple
try:
  tuple1[1] = 'Lucky'
except TypeError as e:
  print(e)

'tuple' object does not support item assignment


**Explanation** = When I try to change the second name in the tuple, Python raises a TypeError because tuples are immutable. This means we cannot assign a new value to an existing index in a tuple.


3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [107]:
set={1,2,2,3,3,4,4,5,6,6}
print(set)

{1, 2, 3, 4, 5, 6}


**Explanation** = When we create a set with duplicate values, Python removes the duplicates and leave only unique elements in the set. because, sets are designed to store unique elements, and duplicates are not allowed.


4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [108]:
dict1={'Names':['ajay','sanjay','ramesh'],'age':[22,21,24],'city':['bengaluru','chennai','calcutta']}

In [109]:
dict1

{'Names': ['ajay', 'sanjay', 'ramesh'],
 'age': [22, 21, 24],
 'city': ['bengaluru', 'chennai', 'calcutta']}

In [110]:
# uptading the age
dict1['age']=[25,26,27]
dict1

{'Names': ['ajay', 'sanjay', 'ramesh'],
 'age': [25, 26, 27],
 'city': ['bengaluru', 'chennai', 'calcutta']}

In [111]:
# Adding a new key 'email'
dict1['email']=['ajay@gmail.com','sanjay@gmail.com','ramesh@gmail.com']
dict1

{'Names': ['ajay', 'sanjay', 'ramesh'],
 'age': [25, 26, 27],
 'city': ['bengaluru', 'chennai', 'calcutta'],
 'email': ['ajay@gmail.com', 'sanjay@gmail.com', 'ramesh@gmail.com']}

In [112]:
# Final Dictionary
dict1

{'Names': ['ajay', 'sanjay', 'ramesh'],
 'age': [25, 26, 27],
 'city': ['bengaluru', 'chennai', 'calcutta'],
 'email': ['ajay@gmail.com', 'sanjay@gmail.com', 'ramesh@gmail.com']}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [113]:
def vote_eligibility(age):
  if age>=18:
    print("You are eligible to vote")
  else:
    print("You are not eligible to vote")
age = int(input("Enter your age: "))
vote_eligibility(age)

Enter your age: 20
You are eligible to vote


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [114]:
def marks_grade(marks):
  if marks>=90:
    print("Your grade is A")
  elif marks>=75 and marks<=89:
    print("Your grade is B")
  elif marks>=50 and marks<=74:
    print("Your grade is C")
  else:
    print("You are Fail")
marks=int(input("Enter your marks: "))
marks_grade(marks)

Enter your marks: 92
Your grade is A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [115]:
def check_number(n):
  if n>0:
    if n%2==0:
      print('n is a positive and even number.')
    else:
      print('n is a positive and odd number.')
  elif n==0:
    print('n is zero.')
  else:
    print('n is a negative number.')
n=int(input('Enter a number: '))
check_number(n)


Enter a number: 7
n is a positive and odd number.


**Section B: Numpy**

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [116]:
#A scalar using np.array(5)
import numpy as np
scalar = np.array(5)
print("Scalar:")
print(scalar)

Scalar:
5


In [117]:
# A 1D array with values 1 to 5
one_dim=np.array([1,2,3,4,5])
one_dim

array([1, 2, 3, 4, 5])

In [118]:
# A 2D array (2x3) with values from 10 to 60 in steps of 10
two_dim=np.array([[10, 20, 30], [40, 50, 60]])
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [119]:
a=np.random.randint(0,100,16).reshape(4,4)
a

array([[12, 54, 56,  3],
       [62, 44, 69, 16],
       [ 5, 93, 32, 48],
       [62, 46,  6, 45]])

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [120]:
# Create a 2D Array of Shape(3x3)
two_dim= np.array([[2,4,6],[8,10,12],[14,16,18]])
two_dim

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [121]:
# Converting 2D into a Pandas DataFrame and adding column names:'A','B','C'.
import pandas as pd
df=pd.DataFrame(two_dim,columns=['A','B','C'])
df

A   B   C
0   2   4   6
1   8  10  12
2  14  16  18

**Section C: Exploring Pandas**

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [123]:
# Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'.
df= {'Name': ['Johny', 'Anil', 'harsha', 'Linga', 'Anil', 'Lucky', 'Babu', 'Emma', 'Mitch', 'Sara'],
    'Age': [28, 24, 35, 32, 24, 24, 40, 29, 33, 30],
    'City': ['New York', 'Paris', 'Berlin', 'London', 'Paris', 'Paris', 'Berlin', 'London', 'New York', 'Paris'],
    'Salary': [50000, 60000, 55000, 70000, 60000, 60000, 72000, 62000, 68000, 59000]}

In [124]:
df=pd.DataFrame(df)
df

Name  Age      City  Salary
0   Johny   28  New York   50000
1    Anil   24     Paris   60000
2  harsha   35    Berlin   55000
3   Linga   32    London   70000
4    Anil   24     Paris   60000
5   Lucky   24     Paris   60000
6    Babu   40    Berlin   72000
7    Emma   29    London   62000
8   Mitch   33  New York   68000
9    Sara   30     Paris   59000

In [125]:
# using .info(), .describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [126]:
df.describe()

Age        Salary
count  10.000000     10.000000
mean   29.900000  61600.000000
std     5.279941   6769.211344
min    24.000000  50000.000000
25%    25.000000  59250.000000
50%    29.500000  60000.000000
75%    32.750000  66500.000000
max    40.000000  72000.000000

In [127]:
# select 'name' and 'city' columns
df[['Name','City']]

Name      City
0   Johny  New York
1    Anil     Paris
2  harsha    Berlin
3   Linga    London
4    Anil     Paris
5   Lucky     Paris
6    Babu    Berlin
7    Emma    London
8   Mitch  New York
9    Sara     Paris

In [128]:
# drop 'city' column
df.drop('City',axis=1)

Name  Age  Salary
0   Johny   28   50000
1    Anil   24   60000
2  harsha   35   55000
3   Linga   32   70000
4    Anil   24   60000
5   Lucky   24   60000
6    Babu   40   72000
7    Emma   29   62000
8   Mitch   33   68000
9    Sara   30   59000

In [129]:
# Filling any missing values in 'Salary' column with the mean
mean_salary=df['Salary'].mean()
df['Salary']=df['Salary'].fillna(mean_salary)
print(df)

     Name  Age      City  Salary
0   Johny   28  New York   50000
1    Anil   24     Paris   60000
2  harsha   35    Berlin   55000
3   Linga   32    London   70000
4    Anil   24     Paris   60000
5   Lucky   24     Paris   60000
6    Babu   40    Berlin   72000
7    Emma   29    London   62000
8   Mitch   33  New York   68000
9    Sara   30     Paris   59000


In [130]:
# Remove any duplicate rows
df.drop_duplicates()

Name  Age      City  Salary
0   Johny   28  New York   50000
1    Anil   24     Paris   60000
2  harsha   35    Berlin   55000
3   Linga   32    London   70000
5   Lucky   24     Paris   60000
6    Babu   40    Berlin   72000
7    Emma   29    London   62000
8   Mitch   33  New York   68000
9    Sara   30     Paris   59000