In [7]:
import numpy as np

In [16]:
### one_dim
one_dim= np.array([2,4,6,10,8,19,100])

In [17]:
type(one_dim)

numpy.ndarray

In [18]:
one_dim.ndim

1

In [19]:
one_dim.size

7

In [20]:
one_dim[3]=100

In [21]:
one_dim

array([  2,   4,   6, 100,   8,  19, 100])

In [23]:
np.where(one_dim==8)

(array([4]),)

In [26]:
one_dim1=np.insert(one_dim,5,200)

In [28]:
one_dim

array([  2,   4,   6, 100,   8,  19, 100])

In [29]:
np.delete(one_dim,3)

array([  2,   4,   6,   8,  19, 100])

In [30]:
one_dim

array([  2,   4,   6, 100,   8,  19, 100])

In [31]:
np.max(one_dim)

np.int64(100)

In [32]:
np.min(one_dim)

np.int64(2)

In [33]:
np.mean(one_dim)

np.float64(34.142857142857146)

In [34]:
np.median(one_dim)

np.float64(8.0)

In [35]:
np.sum(one_dim)

np.int64(239)

In [36]:
np.argmax(one_dim)

np.int64(3)

In [37]:
np.unique(one_dim)

array([  2,   4,   6,   8,  19, 100])

In [49]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [46]:
np.random.randint(1,100,12)

array([89, 71, 14, 43,  3, 41, 49, 52, 63, 19, 90, 74], dtype=int32)

##### Two dimensional Array

In [50]:
two_dim= np.array([[2,4,6],[8,10,12],[14,16,18]])
two_dim

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [51]:
two_dim.ndim

2

In [52]:
two_dim.size

9

In [53]:
two_dim.shape

(3, 3)

In [55]:
two_dim[2,2]=28

In [56]:
two_dim

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 28]])

In [57]:
np.argwhere(two_dim==28)

array([[2, 2]])

In [62]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
two_dim= np.random.randint(1,100,16).reshape(4,4)
two_dim

array([[79, 17, 92, 17],
       [32, 83, 22,  5],
       [69, 36, 38, 20],
       [82, 96, 92, 54]], dtype=int32)

In [69]:
two_dim[0]

array([79, 17, 92, 17], dtype=int32)

In [70]:
two_dim[:3]

array([[79, 17, 92, 17],
       [32, 83, 22,  5],
       [69, 36, 38, 20]], dtype=int32)

In [71]:
two_dim[:,:3]

array([[79, 17, 92],
       [32, 83, 22],
       [69, 36, 38],
       [82, 96, 92]], dtype=int32)

In [72]:
two_dim[[0,1,3]]

array([[79, 17, 92, 17],
       [32, 83, 22,  5],
       [82, 96, 92, 54]], dtype=int32)

In [73]:
two_dim[:,[1,3]]

array([[17, 17],
       [83,  5],
       [36, 20],
       [96, 54]], dtype=int32)

In [74]:
two_dim

array([[79, 17, 92, 17],
       [32, 83, 22,  5],
       [69, 36, 38, 20],
       [82, 96, 92, 54]], dtype=int32)

In [77]:
## axis=0 for rows, axis=1 for columns
np.insert(two_dim,2,[10,20,30,40],axis=1)

array([[79, 17, 10, 92, 17],
       [32, 83, 20, 22,  5],
       [69, 36, 30, 38, 20],
       [82, 96, 40, 92, 54]], dtype=int32)

In [78]:
two_dim

array([[79, 17, 92, 17],
       [32, 83, 22,  5],
       [69, 36, 38, 20],
       [82, 96, 92, 54]], dtype=int32)