In [80]:
import numpy as np

In [81]:
### one_dim
one_dim= np.array([2,4,6,10,8,19,100])

In [82]:
type(one_dim)

numpy.ndarray

In [83]:
one_dim.ndim

1

In [84]:
one_dim.size

7

In [85]:
one_dim[3]=100

In [86]:
one_dim

array([  2,   4,   6, 100,   8,  19, 100])

In [87]:
np.where(one_dim==8)

(array([4]),)

In [88]:
one_dim1=np.insert(one_dim,5,200)

In [89]:
one_dim

array([  2,   4,   6, 100,   8,  19, 100])

In [90]:
np.delete(one_dim,3)

array([  2,   4,   6,   8,  19, 100])

In [91]:
one_dim

array([  2,   4,   6, 100,   8,  19, 100])

In [92]:
np.max(one_dim)

np.int64(100)

In [93]:
np.min(one_dim)

np.int64(2)

In [94]:
np.mean(one_dim)

np.float64(34.142857142857146)

In [95]:
np.median(one_dim)

np.float64(8.0)

In [96]:
np.sum(one_dim)

np.int64(239)

In [97]:
np.argmax(one_dim)

np.int64(3)

In [98]:
np.unique(one_dim)

array([  2,   4,   6,   8,  19, 100])

In [99]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [100]:
np.random.randint(1,100,12)

array([77, 48, 44, 22, 11, 33, 48, 88, 64, 68, 92, 19], dtype=int32)

##### Two dimensional Array

In [102]:
two_dim= np.array([[2,4,6],[8,10,12],[14,16,18]])
two_dim

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [103]:
two_dim.ndim

2

In [104]:
two_dim.size

9

In [105]:
two_dim.shape

(3, 3)

In [107]:
two_dim[2,2]=28

In [108]:
two_dim

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 28]])

In [109]:
np.argwhere(two_dim==28)

array([[2, 2]])

In [62]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [110]:
two_dim= np.random.randint(1,100,16).reshape(4,4)
two_dim

array([[47, 88, 36, 12],
       [87, 75, 55, 44],
       [57, 42, 71, 89],
       [26, 96, 77, 39]], dtype=int32)

In [111]:
two_dim[0]

array([47, 88, 36, 12], dtype=int32)

In [112]:
two_dim[:3]

array([[47, 88, 36, 12],
       [87, 75, 55, 44],
       [57, 42, 71, 89]], dtype=int32)

In [113]:
two_dim[:,:3]

array([[47, 88, 36],
       [87, 75, 55],
       [57, 42, 71],
       [26, 96, 77]], dtype=int32)

In [114]:
two_dim[[0,1,3]]

array([[47, 88, 36, 12],
       [87, 75, 55, 44],
       [26, 96, 77, 39]], dtype=int32)

In [115]:
two_dim[:,[1,3]]

array([[88, 12],
       [75, 44],
       [42, 89],
       [96, 39]], dtype=int32)

In [116]:
two_dim

array([[47, 88, 36, 12],
       [87, 75, 55, 44],
       [57, 42, 71, 89],
       [26, 96, 77, 39]], dtype=int32)

In [117]:
## axis=0 for rows, axis=1 for columns
np.insert(two_dim,2,[10,20,30,40],axis=1)

array([[47, 88, 10, 36, 12],
       [87, 75, 20, 55, 44],
       [57, 42, 30, 71, 89],
       [26, 96, 40, 77, 39]], dtype=int32)

In [118]:
two_dim

array([[47, 88, 36, 12],
       [87, 75, 55, 44],
       [57, 42, 71, 89],
       [26, 96, 77, 39]], dtype=int32)

In [119]:
np.delete(two_dim,1,axis=0)

array([[47, 88, 36, 12],
       [57, 42, 71, 89],
       [26, 96, 77, 39]], dtype=int32)

In [120]:
two_dim

array([[47, 88, 36, 12],
       [87, 75, 55, 44],
       [57, 42, 71, 89],
       [26, 96, 77, 39]], dtype=int32)

In [122]:
np.mean(two_dim)

np.float64(58.8125)

In [124]:
np.sum(two_dim,axis=0)

array([217, 301, 239, 184])

In [126]:
np.max(two_dim,axis=1)

array([88, 87, 89, 96], dtype=int32)

In [127]:
two_dim

array([[47, 88, 36, 12],
       [87, 75, 55, 44],
       [57, 42, 71, 89],
       [26, 96, 77, 39]], dtype=int32)

In [129]:
a= np.random.randint(1,100,4).reshape(2,2)
a

array([[45, 68],
       [93, 82]], dtype=int32)

In [130]:
b= np.random.randint(1,100,4).reshape(2,2)
b

array([[53, 49],
       [ 5, 74]], dtype=int32)

In [131]:
a+b

array([[ 98, 117],
       [ 98, 156]], dtype=int32)

In [132]:
a-b

array([[-8, 19],
       [88,  8]], dtype=int32)

In [133]:
a*b

array([[2385, 3332],
       [ 465, 6068]], dtype=int32)

In [134]:
a/b

array([[ 0.8490566 ,  1.3877551 ],
       [18.6       ,  1.10810811]])

In [136]:
## matrix multiplication
a@b

array([[ 2725,  7237],
       [ 5339, 10625]], dtype=int32)

In [137]:
## Stacking of arrays
np.vstack([a,b])

array([[45, 68],
       [93, 82],
       [53, 49],
       [ 5, 74]], dtype=int32)

In [138]:
np.hstack([a,b])

array([[45, 68, 53, 49],
       [93, 82,  5, 74]], dtype=int32)

In [139]:
np.linalg.det(a)

np.float64(-2633.999999999999)

In [140]:
np.linalg.inv(a)

array([[-0.03113136,  0.02581625],
       [ 0.03530752, -0.01708428]])

In [141]:
np.transpose(a)

array([[45, 93],
       [68, 82]], dtype=int32)

In [143]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [147]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [148]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])